CREATE TABLE STUDENT (
	id INT NOT NULL,
    sname VARCHAR(30),
    address VARCHAR(30),
    sstatus VARCHAR(30)
    );
    
#ALTER TABLE STUDENT ADD CONSTRAINT PK_STUDENT PRIMARY KEY (id);

CREATE TABLE PROFESSOR (
	id INT NOT NULL,
    pname VARCHAR(30),
    deptId VARCHAR(30)
    );
    
#ALTER TABLE STUDENT ADD CONSTRAINT PK_PROFESSOR PRIMARY KEY (id);
    
CREATE TABLE COURSE (
	crsCode VARCHAR(30),
    deptId VARCHAR(30),
    crsName VARCHAR(30),
	descr VARCHAR(50)
    );
    
#ALTER TABLE COURSE ADD CONSTRAINT PK_COURSE PRIMARY KEY (crsCode);

CREATE TABLE TEACHING (
	profId INT NOT NULL,
    crsCode VARCHAR(30),
    semester VARCHAR(30)
    );

#ALTER TABLE TEACHING ADD CONSTRAINT PK_TEACHING PRIMARY KEY (profId, crsCode);

CREATE TABLE TRANSCRIPT (
	studId INT NOT NULL,
    crsCode VARCHAR(30),
    semester VARCHAR(30),
    grade VARCHAR(30)
    );
    
#ALTER TABLE TRANSCRIPT ADD CONSTRAINT PK_TRANSCRIPT PRIMARY KEY (studId, crsCode);


#ALTER TABLE TRANSCRIPT ADD CONSTRAINT FK_TRANSCRIPT_0 FOREIGN KEY (studId) REFERENCES STUDENT (id);
#ALTER TABLE TRANSCRIPT ADD CONSTRAINT FK_TRANSCRIPT_1 FOREIGN KEY (crsCode) REFERENCES COURSE (crsCode);
#ALTER TABLE TEACHING ADD CONSTRAINT FK_TEACHING_0 FOREIGN KEY (profId) REFERENCES PROFESSOR (id);
#ALTER TABLE TEACHING ADD CONSTRAINT FK_TEACHING_1 FOREIGN KEY (crsCode) REFERENCES COURSE (crsCode);